feat(DO-779): Several little improvements and new features
dodevops/terraform-azure-postgresql pull request #1
Opened 2021-08-23 14:45 UTC by timdeluxe

2021-08-24 05:09 UTC, dploeger requested changes

2021-08-24 05:09 UTC, dploeger commented on firewall.tf
> +resource "azurerm_postgresql_firewall_rule" "public" {
This should be explicitly configurable. A default of "if no ips are allowed, all ips are allowed" isn't good IMHO as a user could just as well only allow (internal) subnets to access the server and no external ip at all.

Also, this rule can be achieved by setting the allowed ips to one item ranging from 0.0.0.0 to 255.255.255.255.

2021-08-24 11:51 UTC, ThomasMinor approved these changes

2021-08-26 09:57 UTC, timdeluxe commented
@dploeger Please review the latest changes and approve PR if ok. Thanks.

2021-08-26 10:19 UTC, dploeger commented
> @dploeger Please review the latest changes and approve PR if ok. Thanks.

You can request changes again using the built-in function, but I'll check it out.

2021-08-26 10:20 UTC, dploeger approved these changes

2021-08-26 14:48 UTC, merged